### PR TITLE
Sonata

### PR DESCRIPTION
**Pull request by gwenchee**
This PR addresses https://github.com/arfc/d3ploy/issues/263 by introducing an if statement that circumvents the error that is thrown by Sonata's computer. Previous versions of numpy raise the error but keep going. But, newer versions of numpy stop working.

### CODE REVIEW

**Comment by gwenchee** [comment]
This PR relies on https://github.com/arfc/d3ploy/pull/259. That's why there are so many changes.

**Review by FlanFlanagan — COMMENTED** [review]
I wonder if we should instead wrap all the methods in a try/catch situation, with the fallback just being demand response (using this time steps information, not predicting).

**Review by FlanFlanagan — APPROVED** [review]

**Comment by FlanFlanagan** [comment]
@gwenchee can we remove this PR? It's already solved with #267

**Comment by gwenchee** [comment]
Yup!

**Pull request closed without merging**
