### PR TITLE
Correct develop -> develop

### PR DESCRIPTION
**Pull request by gwenchee**
Correct develop is fixed for all the errors that the develop branch had after https://github.com/ergs/d3ploy/pull/27 PR.

### CODE REVIEW

**Review by FlanFlanagan — COMMENTED** [review]
This test file should just import no_inst.py and call the function from there. 

Having the function fully described in both locations is problematic for updating the function. The function in no_inst might be changed but the test might not. Causing tests to fail or pass and not really reflect the behavior of the module.

**Comment by gwenchee** [comment]
Must close https://github.com/ergs/d3ploy/pull/53 PR first.

**Comment by gwenchee** [comment]
https://github.com/ergs/d3ploy/pull/56 fixes https://github.com/ergs/d3ploy/issues/54.

**Comment by gwenchee** [comment]
Are we good to merge correct develop into develop? @jbae11 @FlanFlanagan

**Pull request merged**
