### PR TITLE
Renametabless

### PR DESCRIPTION
**Pull request by gwenchee**
This PR addresses https://github.com/ergs/d3ploy/issues/184

### CODE REVIEW

**Comment by FlanFlanagan** [comment]
@gwenchee This is not passing CI. Looks like you need to update the tests with the new table names

**Comment by gwenchee** [comment]
I think this might be due to the wrong cycamore (not the one that has record time series added for supply and demand for specific facilities) being installed on the circle ci

**Comment by gwenchee** [comment]
So i checked again, and the reason why the ci is not passing is that it is using an old version of cycamore that does not include the timeseries tables d3ploy relies on. Do you know how we can update it? @FlanFlanagan . Should we merge this for now?

**Comment by FlanFlanagan** [comment]
@gwenchee Do you have a PR on for the cycamore update, or do we need to update the dockers?

**Pull request merged**
